services:
  mysql:
    image: mysql:8.0
    container_name: tritium-mysql
    env_file: [.env]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Shanghai
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - tritium_mysql:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro

  redis:
    image: redis:7
    container_name: tritium-redis
    env_file: [.env]
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server","--appendonly","yes","--requirepass","${REDIS_PASSWORD}"]
    volumes:
      - tritium_redis:/data

volumes:
  tritium_mysql:
  tritium_redis:
